// don't edit this file please use npm run generate:element
import { getElementByIdStrict } from './utils/getElementByIdStrict'
export const trackJson = /*#__PURE__*/ getElementByIdStrict<HTMLTextAreaElement>("trackJson");
export const fileInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("fileInput");
export const loadTrackBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("loadTrackBtn");
export const mapCanvas = /*#__PURE__*/ getElementByIdStrict<HTMLElement>("mapCanvas");
export const selectedInfo = /*#__PURE__*/ getElementByIdStrict<HTMLParagraphElement>("selectedInfo");
export const rotationInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("rotationInput");
export const rotationRangeInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("rotationRangeInput");
export const scaleYInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("scaleYInput");
export const scaleZInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("scaleZInput");
export const posXInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("posXInput");
export const posYInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("posYInput");
export const posZInput = /*#__PURE__*/ getElementByIdStrict<HTMLInputElement>("posZInput");
export const deleteConfirmModal = /*#__PURE__*/ getElementByIdStrict<HTMLDivElement>("deleteConfirmModal");
export const deleteConfirmBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("deleteConfirmBtn");
export const deleteCancelBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("deleteCancelBtn");
export const deleteBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("deleteBtn");
export const autoRotationBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("autoRotationBtn");
export const applyBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("applyBtn");
export const downloadBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("downloadBtn");
export const clipboardBtn = /*#__PURE__*/ getElementByIdStrict<HTMLButtonElement>("clipboardBtn");
